name: tracking_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.12.3
  permission_handler: ^11.0.0
  pusher_channels_flutter: ^2.5.0
  http: ^0.13.6
  geolocator: ^10.1.0
  google_maps_custom_marker: ^1.0.3
  persistent_bottom_nav_bar: ^6.2.1
  widget_to_marker: ^1.0.6
  dio: ^5.8.0+1
  shared_preferences: ^2.5.3
  flutter_secure_storage:
    path: lib_plugins/flutter_secure_storage
  email_validator: ^3.0.0
  loading_animation_widget: ^1.3.0
  awesome_dialog: ^3.2.1
  flutter_polyline_points: ^1.0.0
  gap: ^3.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/user_image.png

